### ISSUE TITLE
Chart for plot 2D mathematical data

### ISSUE THREAD

**Issue by Kvaz1r** [wxIshiko/wxCharts#4]
Will realized chart to plot mathematical functions in two-dimensional space? With support for coordinate grid, zoom, etc... like OxyPlot for WPF or ZedGraph for .Net.

**Comment by xleclercq** [comment]
What do you have in mind? For instance drawing a function y = f(x) on a grid. The user would specify the start and end point on the x axis and the function would be drawn. 
Oxyplot is under MIT license so I can easily reproduce its functionality but it's going to take some time before I can start on that since I have a few other things to do before that.

**Comment by Kvaz1r** [comment]
Yes, right. For example we have function f = sin(x) and some array with points {0:pi/100:2*pi;} . It is necessary plot the graph of the function. If the connection between points is not needed, then great suitable scatter chart. If not, then the best options looks wxlinechart. But if need add another data ( z = cos(x) for {-pi:pi/100:pi;}) then this type is not suitable, because labels is restricted by the first set of points. And with a grid for such graphics sometimes better visually perceived.
